package Vistas;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import Controlador.cls_Familiar;
import Controlador.cls_Personal;
import Controlador.cls_Academico;
import Controlador.cls_Experiencia_lab;
import java.awt.event.ActionEvent;

/**
 *
 * @author Sala102
 */
public class frm_registro extends javax.swing.JFrame {
    LinkedList<cls_Personal> datosPersonales = new LinkedList<>();
    LinkedList<cls_Familiar> datosFamiliar = new LinkedList<>();
    LinkedList<cls_Academico> datosAcademicos = new LinkedList<>();
    LinkedList<cls_Experiencia_lab> datosLaborales = new LinkedList<>();
    int posicionInt;
    boolean swBln;

    /**
     * Creates new form frm_registro
     */
    public frm_registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_contacto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_Actualizar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_perfil = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombreFamiliar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_parentezco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_contactoFamiliar = new javax.swing.JTextField();
        btn_mostrarFamiliar = new javax.swing.JButton();
        btn_nuevoFamiliar = new javax.swing.JButton();
        btn_registrarFamiliar = new javax.swing.JButton();
        btn_nuevo_registro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_instituto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_añoGrado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_nivel = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_contactoEstudio = new javax.swing.JTextField();
        btn_mostrarEstudios = new javax.swing.JButton();
        btn_nuevoEstudios = new javax.swing.JButton();
        btn_registrarEstudios = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_empresa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_contactoLaboral = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_tiempoLaboral = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_cargoLaboral = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btn_mostrarLaboral = new javax.swing.JButton();
        btn_nuevoLaboral = new javax.swing.JButton();
        btn_registrarLaboral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formato de registro de candidatos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos Personales");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 74, 251, -1));

        jLabel3.setText("Identificacion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, -1, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 102, 251, -1));

        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 136, -1, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 130, 251, -1));

        jLabel5.setText("Contacto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 161, -1, -1));
        getContentPane().add(txt_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 158, 251, -1));

        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 189, -1, -1));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 186, 251, -1));

        jLabel7.setText("Correo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 217, -1, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 214, 251, -1));

        jLabel8.setText("Perfil:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 242, -1, -1));

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        txt_perfil.setColumns(20);
        txt_perfil.setRows(5);
        jScrollPane1.setViewportView(txt_perfil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 242, 251, 80));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Datos Familiares");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 392, 250, -1));

        jLabel10.setText("Nombres:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 423, -1, -1));
        getContentPane().add(txt_nombreFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 420, 250, -1));

        jLabel11.setText("Parentezco:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 451, -1, -1));

        txt_parentezco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_parentezcoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_parentezco, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 448, 250, -1));

        jLabel12.setText("Contacto:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 479, -1, -1));
        getContentPane().add(txt_contactoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 476, 250, -1));

        btn_mostrarFamiliar.setText("Mostrar");
        btn_mostrarFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarFamiliarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrarFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 504, 84, -1));

        btn_nuevoFamiliar.setText("Nuevo");
        btn_nuevoFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoFamiliarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevoFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 504, 78, -1));

        btn_registrarFamiliar.setText("Registrar");
        btn_registrarFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarFamiliarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 504, -1, -1));

        btn_nuevo_registro.setText("Nuevo Registro");
        btn_nuevo_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_registroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 260, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estudios Realizados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(89, 89, 89))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 74, 270, -1));

        jLabel14.setText("Titulo:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 105, -1, -1));

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });
        getContentPane().add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 102, 270, -1));

        jLabel15.setText("IE:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 133, -1, -1));
        getContentPane().add(txt_instituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 270, -1));

        jLabel16.setText("Año G:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 161, -1, -1));
        getContentPane().add(txt_añoGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 158, 270, -1));

        jLabel17.setText("Nivel:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 189, -1, -1));
        getContentPane().add(txt_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 186, 270, -1));

        jLabel18.setText("Contacto:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 217, -1, -1));
        getContentPane().add(txt_contactoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 214, 268, -1));

        btn_mostrarEstudios.setText("Mostrar");
        btn_mostrarEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarEstudiosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrarEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 242, 80, -1));

        btn_nuevoEstudios.setText("Nuevo");
        btn_nuevoEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoEstudiosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevoEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 242, 90, -1));

        btn_registrarEstudios.setText("Registrar");
        btn_registrarEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarEstudiosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 242, 90, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Datos Laborales");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(89, 89, 89))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));
        getContentPane().add(txt_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 270, -1));

        jLabel21.setText("Empresa:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 353, -1, -1));
        getContentPane().add(txt_contactoLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 378, 270, -1));

        jLabel22.setText("Contacto:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 381, -1, -1));
        getContentPane().add(txt_tiempoLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 406, 270, -1));

        jLabel23.setText("Tiempo:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 409, -1, -1));
        getContentPane().add(txt_cargoLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 434, 270, -1));

        jLabel24.setText("Cargo:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 437, -1, -1));

        btn_mostrarLaboral.setText("Mostrar");
        btn_mostrarLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarLaboralActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrarLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 462, 80, -1));

        btn_nuevoLaboral.setText("Nuevo");
        btn_nuevoLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoLaboralActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevoLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 462, 90, -1));

        btn_registrarLaboral.setText("Registrar");
        btn_registrarLaboral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarLaboralActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 462, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void txt_parentezcoActionPerformed(ActionEvent evt) {
        // TODO Auto-generated method stub
    }

    private void fnt_consultarDpersona(int id){
        posicionInt = 0;
        swBln = false;
        for(int i = 0; i < datosPersonales.size(); i++){
                if(id == datosPersonales.get(i).getIdint()){
                    posicionInt = i;
                    swBln = true;
                    break;
                }
        }
        if(swBln == false){
                JOptionPane.showMessageDialog(null, "No se encontro el candidato",
                "Consultar",JOptionPane.ERROR_MESSAGE);
        }else{
                txt_nombre.setText(datosPersonales.get(posicionInt).getNombreStr());
                txt_contacto.setText(datosPersonales.get(posicionInt).getContactoStr());
                txt_direccion.setText(datosPersonales.get(posicionInt).getDireccionStr());
                txt_correo.setText(datosPersonales.get(posicionInt).getCorreoStr());
                txt_perfil.setText(datosPersonales.get(posicionInt).getPerfilStr());
        }
    
    }

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        fnt_consultarDpersona(Integer.parseInt(txt_id.getText()));
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_nuevo_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_registroActionPerformed
        txt_id.setText("");
        txt_nombre.setText("");
        txt_contacto.setText("");
        txt_direccion.setText("");
        txt_correo.setText("");
        txt_perfil.setText("");
        
        txt_nombreFamiliar.setText("");
        txt_parentezco.setText("");
        txt_contactoFamiliar.setText("");

        txt_titulo.setText("");
        txt_instituto.setText("");
        txt_añoGrado.setText("");
        txt_nivel.setText("");
        txt_contactoEstudio.setText("");

        txt_empresa.setText("");
        txt_contactoLaboral.setText("");
        txt_tiempoLaboral.setText("");
        txt_cargoLaboral.setText("");
    }//GEN-LAST:event_btn_nuevo_registroActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void fnt_mostrarEstudios() {
        int id = Integer.parseInt(txt_id.getText());
    
        List<cls_Academico> estudiosPorID = new ArrayList<>();
    
        for (cls_Academico estudios : datosAcademicos) {
            if (estudios.getIdInt() == id) {
                estudiosPorID.add(estudios);
            }
        }
    
        if (estudiosPorID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se encontraron estudios para el ID especificado",
                    "Datos de la Institucion", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    
        Object[][] data = new Object[estudiosPorID.size()][5];
    
        for (int i = 0; i < estudiosPorID.size(); i++) {
            cls_Academico estudios = estudiosPorID.get(i);
            data[i][0] = estudios.getTituloStr();
            data[i][1] = estudios.getInstituStr();
            data[i][2] = estudios.getAño_gradoStr();
            data[i][3] = estudios.getGradoStr();
            data[i][4] = estudios.getContactoStr();
        }
    
        String[] columnNames = {"Titulo", "Institucion", "Año grado", "Nivel", "Contacto"};
    
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
    
        JTable table = new JTable(model);
    
        JOptionPane.showMessageDialog(null, new JScrollPane(table), "Datos de la Institucion",
                JOptionPane.INFORMATION_MESSAGE);
    }
    

    private void btn_mostrarEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarEstudiosActionPerformed
        fnt_mostrarEstudios();
    }//GEN-LAST:event_btn_mostrarEstudiosActionPerformed

    private void fnt_mostrarLaboral() {
        int id = Integer.parseInt(txt_id.getText());

        List<cls_Experiencia_lab> experienciaLabPorID = new ArrayList<>();

    for (cls_Experiencia_lab laboral : datosLaborales) {
        if (laboral.getIdInt() == id) {
            experienciaLabPorID.add(laboral);
        }
    }

    if (experienciaLabPorID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No se encontraron experiencia laboral para el ID especificado",
                "Datos de la experiencia laboral", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    Object[][] data = new Object[experienciaLabPorID.size()][5];

    for (int i = 0; i < experienciaLabPorID.size(); i++) {
        cls_Experiencia_lab laboral = experienciaLabPorID.get(i);
        data[i][0] = laboral.getEmpresaStr();
        data[i][1] = laboral.getContactoStr();
        data[i][2] = laboral.getTiempoStr();
        data[i][3] = laboral.getCargoStr();
    }

    String[] columnNames = {"Empresa", "Contacto", "Tiempo", "Cargo"};

    DefaultTableModel model = new DefaultTableModel(data, columnNames);

    JTable table = new JTable(model);

    JOptionPane.showMessageDialog(null, new JScrollPane(table), "Datos de la experiencia laboral",
    JOptionPane.INFORMATION_MESSAGE);
    }


    private void btn_mostrarLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarLaboralActionPerformed
        fnt_mostrarLaboral();
    }//GEN-LAST:event_btn_mostrarLaboralActionPerformed


    private void fnt_registrarFamiliar() {
        if (datosPersonales.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe registrar datos personales primero",
                    "Registro de Familiar", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete el campo de ID para registrar un familiar",
                    "Registro de Familiar", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        int id = Integer.parseInt(txt_id.getText());
        boolean idEncontrado = false;
        for (int i = 0; i < datosPersonales.size(); i++) {
            cls_Personal personal = datosPersonales.get(i);
            if (personal.getIdint() == id) {
                idEncontrado = true;
                break;
            }
        }
        
    
        if (!idEncontrado) {
            JOptionPane.showMessageDialog(null, "El ID no corresponde a ningún registro de datos personales",
                    "Registro de Familiar", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        String nombre = txt_nombreFamiliar.getText();
        String parentezco = txt_parentezco.getText();
        String contacto = txt_contactoFamiliar.getText();
    
        if (nombre.isEmpty() || parentezco.isEmpty() || contacto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos para registrar un familiar",
                    "Registro de Familiar", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        cls_Familiar familiar = new cls_Familiar(id, nombre, parentezco, contacto);
        datosFamiliar.add(familiar);
    
        JOptionPane.showMessageDialog(null, "Familiar registrado con éxito");
    }
    
    
    
    private void btn_registrarFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarFamiliarActionPerformed
        fnt_registrarFamiliar();
    }//GEN-LAST:event_btn_registrarFamiliarActionPerformed

    private void fnt_mostrarFamilia() {
    if (txt_id.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un ID válido para mostrar la familia",
                "Datos de la Familia", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int id = Integer.parseInt(txt_id.getText());
    List<cls_Familiar> familiaresMostrados = new ArrayList<>();

    for (cls_Familiar familiar : datosFamiliar) {
        if (familiar.getIdInt() == id) {
            familiaresMostrados.add(familiar);
        }
    }

    if (familiaresMostrados.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No se encontraron familiares asociados al ID ingresado",
                "Datos de la Familia", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    Object[][] data = new Object[familiaresMostrados.size()][3];
    for (int i = 0; i < familiaresMostrados.size(); i++) {
        cls_Familiar familiar = familiaresMostrados.get(i);
        data[i][0] = familiar.getNombreStr();
        data[i][1] = familiar.getParentezcoStr();
        data[i][2] = familiar.getContactoStr();
    }

    String[] columnNames = {"Nombre", "Parentezco", "Contacto"};

    DefaultTableModel model = new DefaultTableModel(data, columnNames);
    JTable table = new JTable(model);

    JOptionPane.showMessageDialog(null, new JScrollPane(table), "Datos de la Familia",
            JOptionPane.INFORMATION_MESSAGE);
}


    private void btn_mostrarFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarFamiliarActionPerformed
        fnt_mostrarFamilia();
    }//GEN-LAST:event_btn_mostrarFamiliarActionPerformed

    private void fnt_registrarEstudios() {
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un ID válido para registrar los estudios",
                    "Registro de Estudios", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        if (datosPersonales.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, registre primero los datos personales",
                    "Registro de Estudios", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        int id = Integer.parseInt(txt_id.getText());
        boolean idEncontrado = false;
        for (int i = 0; i < datosPersonales.size(); i++) {
            cls_Personal personal = datosPersonales.get(i);
            if (personal.getIdint() == id) {
                idEncontrado = true;
                break;
            }
        }
        if (!idEncontrado) {
            JOptionPane.showMessageDialog(null, "El ID ingresado no corresponde a un registro de datos personales",
                    "Registro de Estudios", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        String titulo = txt_titulo.getText();
        String institu = txt_instituto.getText();
        String año_grado = txt_añoGrado.getText();
        String grado = txt_nivel.getText();
        String contacto = txt_contactoEstudio.getText();
    
        if (titulo.isEmpty() || institu.isEmpty() || año_grado.isEmpty() || grado.isEmpty() || contacto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos para registrar",
                    "Registro de Estudios", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        cls_Academico estudios = new cls_Academico(id, titulo, institu, año_grado, grado, contacto);
        datosAcademicos.add(estudios);
    
        JOptionPane.showMessageDialog(null, "Estudio registrado con éxito");
    }
    

    private void btn_registrarEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarEstudiosActionPerformed
        fnt_registrarEstudios();
    }//GEN-LAST:event_btn_registrarEstudiosActionPerformed

    private void fnt_registrarLaboral() {
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un ID válido para registrar la experiencia laboral",
                    "Registro de Experiencia Laboral", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        if (datosPersonales.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, registre primero los datos personales",
                    "Registro de Experiencia Laboral", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        int id = Integer.parseInt(txt_id.getText());
        boolean idEncontrado = false;
        for (int i = 0; i < datosPersonales.size(); i++) {
            cls_Personal personal = datosPersonales.get(i);
            if (personal.getIdint() == id) {
                idEncontrado = true;
                break;
            }
        }
        
        if (!idEncontrado) {
            JOptionPane.showMessageDialog(null, "El ID ingresado no corresponde a un registro de datos personales",
                    "Registro de Experiencia Laboral", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        
        String empresa = txt_empresa.getText();
        String contacto = txt_contactoLaboral.getText();
        String tiempo = txt_tiempoLaboral.getText();
        String cargo = txt_cargoLaboral.getText();
    
        if (empresa.isEmpty() || contacto.isEmpty() || tiempo.isEmpty() || cargo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos para registrar",
                    "Registro de Experiencia Laboral", JOptionPane.ERROR_MESSAGE);
            return;
        }
    
        
        cls_Experiencia_lab Laboral = new cls_Experiencia_lab(id, empresa, contacto, tiempo, cargo);
        datosLaborales.add(Laboral);
    
        JOptionPane.showMessageDialog(null, "Experiencia laboral registrada con éxito");
    }
    

    private void btn_registrarLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarLaboralActionPerformed
        fnt_registrarLaboral();
    }//GEN-LAST:event_btn_registrarLaboralActionPerformed

    private void btn_nuevoEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoEstudiosActionPerformed
        txt_titulo.setText("");
        txt_instituto.setText("");
        txt_añoGrado.setText("");
        txt_nivel.setText("");
        txt_contactoEstudio.setText("");
    }//GEN-LAST:event_btn_nuevoEstudiosActionPerformed

    private void btn_nuevoLaboralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoLaboralActionPerformed
        txt_empresa.setText("");
        txt_contactoLaboral.setText("");
        txt_tiempoLaboral.setText("");
        txt_cargoLaboral.setText("");
    }//GEN-LAST:event_btn_nuevoLaboralActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void fnt_actualizarDpersona(){
        datosPersonales.get(posicionInt).setNombreStr(txt_nombre.getText());
        datosPersonales.get(posicionInt).setContactoStr(txt_contacto.getText());
        datosPersonales.get(posicionInt).setDireccionStr(txt_direccion.getText());
        datosPersonales.get(posicionInt).setCorreoStr(txt_correo.getText());
        datosPersonales.get(posicionInt).setPerfilStr(txt_perfil.getText());
        JOptionPane.showMessageDialog(null, "Datos actualizados con exito");
    }

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_ActualizarActionPerformed
        fnt_actualizarDpersona();
    }// GEN-LAST:event_btn_ActualizarActionPerformed

    private void fnt_registrarDpersona(int id, String nombre, String contacto, String direccion, 
    String correo, String perfil){
        datosPersonales.add(new cls_Personal(id, nombre, contacto, direccion, correo, perfil));
        JOptionPane.showMessageDialog(null, "Candidato registrado con exito");
    }
    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_registrarActionPerformed
        fnt_registrarDpersona(Integer.parseInt(txt_id.getText()), txt_nombre.getText(),txt_contacto.getText(),
        txt_direccion.getText(),txt_correo.getText(),txt_perfil.getText());
    }// GEN-LAST:event_btn_registrarActionPerformed

    private void btn_nuevoFamiliarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_nuevoActionPerformed
        txt_nombreFamiliar.setText("");
        txt_parentezco.setText("");
        txt_contactoFamiliar.setText("");
    }// GEN-LAST:event_btn_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_registro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_registro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_registro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_registro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_mostrarEstudios;
    private javax.swing.JButton btn_mostrarFamiliar;
    private javax.swing.JButton btn_mostrarLaboral;
    private javax.swing.JButton btn_nuevoEstudios;
    private javax.swing.JButton btn_nuevoFamiliar;
    private javax.swing.JButton btn_nuevoLaboral;
    private javax.swing.JButton btn_nuevo_registro;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_registrarEstudios;
    private javax.swing.JButton btn_registrarFamiliar;
    private javax.swing.JButton btn_registrarLaboral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_añoGrado;
    private javax.swing.JTextField txt_cargoLaboral;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_contactoEstudio;
    private javax.swing.JTextField txt_contactoFamiliar;
    private javax.swing.JTextField txt_contactoLaboral;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_instituto;
    private javax.swing.JTextField txt_nivel;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreFamiliar;
    private javax.swing.JTextField txt_parentezco;
    private javax.swing.JTextArea txt_perfil;
    private javax.swing.JTextField txt_tiempoLaboral;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
