package Vistas;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import javax.swing.JOptionPane;

import Controladores.cls_persona;

public class frm_datos extends javax.swing.JFrame {

        LinkedList<cls_persona> datosPersonales = new LinkedList<>();
        int posicionInt;
        boolean swBln;

        /**
         * Creates new form frm_datos
         */
        public frm_datos() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                btn_registrar = new javax.swing.JButton();
                btn_nuevo = new javax.swing.JButton();
                btn_consultar = new javax.swing.JButton();
                btn_actualizar = new javax.swing.JButton();
                jDesktopPane1 = new javax.swing.JDesktopPane();
                jPanel8 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txt_identificacion = new javax.swing.JTextField();
                jPanel4 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                txt_primer_nombre = new javax.swing.JTextField();
                jPanel5 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                txt_segundo_nombre = new javax.swing.JTextField();
                jPanel6 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                txt_primer_apellido = new javax.swing.JTextField();
                jPanel7 = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                txt_segundo_apellido = new javax.swing.JTextField();
                txt_edad = new javax.swing.JTextField();
                jPanel10 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jPanel11 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                txt_correo = new javax.swing.JTextField();
                txt_contacto = new javax.swing.JTextField();
                jPanel12 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jPanel13 = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();
                txt_fecha = new javax.swing.JTextField();
                jPanel14 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                txt_ciudad_origen = new javax.swing.JTextField();
                jPanel15 = new javax.swing.JPanel();
                jLabel14 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txa_perfil = new javax.swing.JTextArea();
                txt_profesion = new javax.swing.JTextField();
                jPanel16 = new javax.swing.JPanel();
                jLabel13 = new javax.swing.JLabel();
                jPanel17 = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                txa_tecnologias = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(15, 69, 113));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Formulario: Hoja de vida");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(318, 318, 318)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel2.setBackground(new java.awt.Color(132, 145, 179));

                btn_registrar.setBackground(new java.awt.Color(203, 215, 178));
                btn_registrar.setText("Registrar");
                btn_registrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_registrarActionPerformed(evt);
                        }
                });

                btn_nuevo.setBackground(new java.awt.Color(203, 215, 178));
                btn_nuevo.setText("Nuevo");
                btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_nuevoActionPerformed(evt);
                        }
                });

                btn_consultar.setBackground(new java.awt.Color(203, 215, 178));
                btn_consultar.setText("Consultar");
                btn_consultar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_consultarActionPerformed(evt);
                        }
                });

                btn_actualizar.setBackground(new java.awt.Color(203, 215, 178));
                btn_actualizar.setText("Actualizar");
                btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btn_actualizarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(270, 270, 270)
                                                                .addComponent(btn_nuevo)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn_registrar)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn_consultar)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btn_actualizar)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btn_registrar)
                                                                                .addComponent(btn_nuevo)
                                                                                .addComponent(btn_consultar)
                                                                                .addComponent(btn_actualizar))
                                                                .addContainerGap()));

                jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 69, 113), 5, true));
                jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel3.setBackground(new java.awt.Color(15, 69, 113));
                jPanel3.setAlignmentY(0.0F);

                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Identificación");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2)
                                                                .addContainerGap(28, Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2));

                jPanel8.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 106, -1));

                txt_identificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_identificacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_identificacion.setAlignmentY(0.0F);
                jPanel8.add(txt_identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, -1));

                jPanel4.setBackground(new java.awt.Color(15, 69, 113));
                jPanel4.setAlignmentY(0.0F);

                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Primer Nombre");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)
                                                                .addContainerGap(18, Short.MAX_VALUE)));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3));

                jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 106, -1));

                txt_primer_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_primer_nombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_primer_nombre.setAlignmentY(0.0F);
                jPanel8.add(txt_primer_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, -1));

                jPanel5.setBackground(new java.awt.Color(15, 69, 113));
                jPanel5.setAlignmentY(0.0F);

                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Segundo Nombre");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel4)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4));

                jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

                txt_segundo_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_segundo_nombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_segundo_nombre.setAlignmentY(0.0F);
                jPanel8.add(txt_segundo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, -1));

                jPanel6.setBackground(new java.awt.Color(15, 69, 113));
                jPanel6.setAlignmentY(0.0F);

                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Primer Apellido");

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel5)
                                                                .addContainerGap(18, Short.MAX_VALUE)));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING));

                jPanel8.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 106, -1));

                txt_primer_apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_primer_apellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_primer_apellido.setAlignmentY(0.0F);
                txt_primer_apellido.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_primer_apellidoActionPerformed(evt);
                        }
                });
                jPanel8.add(txt_primer_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 252, -1));

                jPanel7.setBackground(new java.awt.Color(15, 69, 113));
                jPanel7.setAlignmentY(0.0F);

                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Segundo Apellido");

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel6)
                                                                .addContainerGap(20, Short.MAX_VALUE)));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6));

                jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));

                txt_segundo_apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_segundo_apellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_segundo_apellido.setAlignmentY(0.0F);
                jPanel8.add(txt_segundo_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 252, -1));

                txt_edad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_edad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_edad.setAlignmentY(0.0F);
                jPanel8.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 250, -1));

                jPanel10.setBackground(new java.awt.Color(15, 69, 113));
                jPanel10.setAlignmentY(0.0F);

                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Edad");

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel10Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel8)
                                                                .addContainerGap(38, Short.MAX_VALUE)));
                jPanel10Layout.setVerticalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8));

                jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 70, -1));

                jPanel11.setBackground(new java.awt.Color(15, 69, 113));
                jPanel11.setAlignmentY(0.0F);

                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Correo electrónico");

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel11Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel9)
                                                                .addContainerGap(26, Short.MAX_VALUE)));
                jPanel11Layout.setVerticalGroup(
                                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9));

                jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 130, -1));

                txt_correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_correo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_correo.setAlignmentY(0.0F);
                jPanel8.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 250, 30));

                txt_contacto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_contacto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_contacto.setAlignmentY(0.0F);
                jPanel8.add(txt_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 250, -1));

                jPanel12.setBackground(new java.awt.Color(15, 69, 113));
                jPanel12.setAlignmentY(0.0F);

                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText("Contacto");

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel10)
                                                                .addContainerGap(15, Short.MAX_VALUE)));
                jPanel12Layout.setVerticalGroup(
                                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10));

                jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 70, -1));

                jPanel13.setBackground(new java.awt.Color(15, 69, 113));
                jPanel13.setAlignmentY(0.0F);

                jLabel11.setForeground(new java.awt.Color(255, 255, 255));
                jLabel11.setText("Fecha de nacimiento");

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel13Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel11)
                                                                .addContainerGap(14, Short.MAX_VALUE)));
                jPanel13Layout.setVerticalGroup(
                                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11));

                jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 130, -1));

                txt_fecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_fecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_fecha.setAlignmentY(0.0F);
                jPanel8.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 250, -1));

                jPanel14.setBackground(new java.awt.Color(15, 69, 113));
                jPanel14.setAlignmentY(0.0F);

                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("Ciudad de origen");

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel12)
                                                                .addContainerGap(23, Short.MAX_VALUE)));
                jPanel14Layout.setVerticalGroup(
                                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12));

                jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, -1));

                txt_ciudad_origen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_ciudad_origen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_ciudad_origen.setAlignmentY(0.0F);
                jPanel8.add(txt_ciudad_origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 257, -1));

                jPanel15.setBackground(new java.awt.Color(15, 69, 113));
                jPanel15.setAlignmentY(0.0F);

                jLabel14.setForeground(new java.awt.Color(255, 255, 255));
                jLabel14.setText("Perfil profesional");

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel15Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel14)
                                                                .addContainerGap(210, Short.MAX_VALUE)));
                jPanel15Layout.setVerticalGroup(
                                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14));

                jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 27, 305, -1));

                txa_perfil.setColumns(20);
                txa_perfil.setLineWrap(true);
                txa_perfil.setRows(5);
                jScrollPane1.setViewportView(txa_perfil);

                jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 49, 305, 80));

                txt_profesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                txt_profesion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txt_profesion.setAlignmentY(0.0F);
                jPanel8.add(txt_profesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 157, 305, -1));

                jPanel16.setBackground(new java.awt.Color(15, 69, 113));
                jPanel16.setAlignmentY(0.0F);

                jLabel13.setForeground(new java.awt.Color(255, 255, 255));
                jLabel13.setText("Profesión");

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel13)
                                                                .addContainerGap(249, Short.MAX_VALUE)));
                jPanel16Layout.setVerticalGroup(
                                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13));

                jPanel8.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 135, 305, -1));

                jPanel17.setBackground(new java.awt.Color(15, 69, 113));
                jPanel17.setAlignmentY(0.0F);

                jLabel15.setForeground(new java.awt.Color(255, 255, 255));
                jLabel15.setText("Tecnologías que domina");

                javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
                jPanel17.setLayout(jPanel17Layout);
                jPanel17Layout.setHorizontalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel17Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel15)
                                                                .addContainerGap(169, Short.MAX_VALUE)));
                jPanel17Layout.setVerticalGroup(
                                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15));

                jPanel8.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 195, 305, -1));

                txa_tecnologias.setColumns(20);
                txa_tecnologias.setLineWrap(true);
                txa_tecnologias.setRows(5);
                jScrollPane2.setViewportView(txa_tecnologias);

                jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 229, 305, 80));

                jDesktopPane1.setLayer(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
                jDesktopPane1.setLayout(jDesktopPane1Layout);
                jDesktopPane1Layout.setHorizontalGroup(
                                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jDesktopPane1Layout.setVerticalGroup(
                                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jDesktopPane1)
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jDesktopPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(58, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void fnt_actualizar() {
                datosPersonales.get(posicionInt).setIdStr(txt_identificacion.getText());

                datosPersonales.get(posicionInt).setP_nombreStr(txt_primer_nombre.getText());
                datosPersonales.get(posicionInt).setS_nombreStr(txt_segundo_nombre.getText());
                datosPersonales.get(posicionInt).setP_apellidoStr(txt_primer_apellido.getText());
                datosPersonales.get(posicionInt).setS_apellidoStr(txt_segundo_apellido.getText());
                datosPersonales.get(posicionInt).setEdadStr(txt_edad.getText());
                datosPersonales.get(posicionInt).setCorreoStr(txt_correo.getText());
                datosPersonales.get(posicionInt).setContactoStr(txt_contacto.getText());
                datosPersonales.get(posicionInt).setFecha_nacStr(txt_fecha.getText());
                datosPersonales.get(posicionInt).setCiudadStr(txt_ciudad_origen.getText());
                datosPersonales.get(posicionInt).setPerfilStr(txa_perfil.getText());
                datosPersonales.get(posicionInt).setProfesionStr(txt_profesion.getText());
                datosPersonales.get(posicionInt).setTecnologiaStr(txa_tecnologias.getText());

                JOptionPane.showMessageDialog(null, "Datos actualizados con exito");
        }

        private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_actualizarActionPerformed
                fnt_actualizar();
        }// GEN-LAST:event_btn_actualizarActionPerformed

        private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_nuevoActionPerformed
                txt_identificacion.setText("");
                txt_primer_nombre.setText("");
                txt_segundo_nombre.setText("");
                txt_primer_apellido.setText("");
                txt_segundo_apellido.setText("");
                txt_edad.setText("");
                txt_correo.setText("");
                txt_contacto.setText("");
                txt_fecha.setText("");
                txt_ciudad_origen.setText("");
                txa_perfil.setText("");
                txt_profesion.setText("");
                txa_tecnologias.setText("");

        }// GEN-LAST:event_btn_nuevoActionPerformed

        private void fnt_consultar(String id) {
                posicionInt = 0;
                swBln = false;
                for (int i = 0; i < datosPersonales.size(); i++) {
                        if (id.equals(datosPersonales.get(i).getIdStr())) {
                                posicionInt = i;
                                swBln = true;
                                break;
                        }
                }

                if (swBln == false) {
                        JOptionPane.showMessageDialog(null, "No se encontró el candidato",
                                        "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                } else {
                        txt_identificacion.setText(datosPersonales.get(posicionInt).getIdStr());
                        txt_primer_nombre.setText(datosPersonales.get(posicionInt).getP_nombreStr());
                        txt_segundo_nombre.setText(datosPersonales.get(posicionInt).getS_nombreStr());
                        txt_primer_apellido.setText(datosPersonales.get(posicionInt).getP_apellidoStr());
                        txt_segundo_apellido.setText(datosPersonales.get(posicionInt).getS_apellidoStr());
                        txt_edad.setText(datosPersonales.get(posicionInt).getEdadStr());
                        txt_correo.setText(datosPersonales.get(posicionInt).getCorreoStr());
                        txt_contacto.setText(datosPersonales.get(posicionInt).getContactoStr());
                        txt_fecha.setText(datosPersonales.get(posicionInt).getFecha_nacStr());
                        txt_ciudad_origen.setText(datosPersonales.get(posicionInt).getCiudadStr());
                        txa_perfil.setText(datosPersonales.get(posicionInt).getPerfilStr());
                        txt_profesion.setText(datosPersonales.get(posicionInt).getProfesionStr());
                        txa_tecnologias.setText(datosPersonales.get(posicionInt).getTecnologiaStr());

                }

        }

        private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_consultarActionPerformed
                fnt_consultar(txt_identificacion.getText());
        }// GEN-LAST:event_btn_consultarActionPerformed

        private void fnt_registrar() {
                String id = txt_identificacion.getText();
                String pNombre = txt_primer_nombre.getText();
                String sNombre = txt_segundo_nombre.getText();
                String pApellido = txt_primer_apellido.getText();
                String sApellido = txt_segundo_apellido.getText();
                String edad = txt_edad.getText();
                String correo = txt_correo.getText();
                String contacto = txt_contacto.getText();
                String fechaNacimiento = txt_fecha.getText();
                String ciudad = txt_ciudad_origen.getText();
                String perfil = txa_perfil.getText();
                String profesion = txt_profesion.getText();
                String tecnologias = txa_tecnologias.getText();

                List<String> errores = new ArrayList<>();
                if (fnt_validaridentidicacion(id) == false) {
                        errores.add("Identificacion");
                }
                if (fnt_validarnombre(pNombre) == false) {
                        errores.add("Primer nombre");
                }
                if (fnt_validarnombre(sNombre) == false) {
                        errores.add("Segundo nombre");
                }
                if (fnt_validarnombre(pApellido) == false) {
                        errores.add("Primer apellido");
                }
                if (fnt_validarnombre(sApellido) == false) {
                        errores.add("Segundo apellido");
                }
                if (fnt_validaredad(edad) == false) {
                        errores.add("Edad");
                }
                if (fnt_validarcorreo(correo) == false) {
                        errores.add("Correo electronico");
                }
                if (fnt_validarcontacto(contacto) == false) {
                        errores.add("Contacto");
                }
                if (fnt_validarfnacimiento(fechaNacimiento) == false) {
                        errores.add("Fecha de nacimiento");
                }
                if (fnt_validarciudad(ciudad) == false) {
                        errores.add("Ciudad de origen");
                }

                if (errores.isEmpty() == false) {
                        String mensajeError = "Se encontraron errores:\n" + String.join("\n", errores);
                        JOptionPane.showMessageDialog(null, mensajeError);
                        return;
                }

                datosPersonales.add(new cls_persona(id, pNombre, sNombre, pApellido, sApellido, edad, correo, contacto,
                                fechaNacimiento, ciudad, perfil, profesion, tecnologias));

                JOptionPane.showMessageDialog(null, "Registrado con éxito");

        }

        private static boolean fnt_validarnombre(String nombre) {
                return nombre.matches("^([A-Z]+[ ]?){1,20}$");
        }

        private static boolean fnt_validaridentidicacion(String numero) {
                return numero.matches("[0-9]{10}");
        }

        private static boolean fnt_validaredad(String edad) {
                return edad.matches("^\\d{0,3}$");

        }

        private static boolean fnt_validarcorreo(String correo) {
                return correo.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$");
        }

        private static boolean fnt_validarcontacto(String contacto) {
                return contacto.matches("[0-9]{10}");
        }

        private static boolean fnt_validarfnacimiento(String fnacimiento) {
                return fnacimiento.matches("^(?:3[01]|[12][0-9]|0?[1-9])([\\-/.])(0?[1-9]|1[0-2])\\1\\d{4}$");
        }

        private static boolean fnt_validarciudad(String ciudad) {
                return ciudad.matches("^[a-zA-Z0-9áéíóúü ]{1,20}$");
        }

        private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_registrarActionPerformed
                fnt_registrar();
        }// GEN-LAST:event_btn_registrarActionPerformed

        private void txt_primer_apellidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_primer_apellidoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_primer_apellidoActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(frm_datos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(frm_datos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(frm_datos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(frm_datos.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new frm_datos().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_actualizar;
        private javax.swing.JButton btn_consultar;
        private javax.swing.JButton btn_nuevo;
        private javax.swing.JButton btn_registrar;
        private javax.swing.JDesktopPane jDesktopPane1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel17;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea txa_perfil;
        private javax.swing.JTextArea txa_tecnologias;
        private javax.swing.JTextField txt_ciudad_origen;
        private javax.swing.JTextField txt_contacto;
        private javax.swing.JTextField txt_correo;
        private javax.swing.JTextField txt_edad;
        private javax.swing.JTextField txt_fecha;
        private javax.swing.JTextField txt_identificacion;
        private javax.swing.JTextField txt_primer_apellido;
        private javax.swing.JTextField txt_primer_nombre;
        private javax.swing.JTextField txt_profesion;
        private javax.swing.JTextField txt_segundo_apellido;
        private javax.swing.JTextField txt_segundo_nombre;
        // End of variables declaration//GEN-END:variables
}
        
        
        
        
        
        
        
        
        
        
        
        
        
        